#!/usr/bin/env bash
# This file will accept 4 parameters and its purpose is to transfer a file
# from the client to the server
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
if [ $# -eq 4 ]
then
	scp -o StrictHostKeyChecking=no -i $1 $3"@"$2":~/" $4
else
	scp -o StrictHostKeyChecking=no $1 $3"@"$2":~/"
fi
