#!/usr/bin/env bash
# This file will accept 4 parameters and its purpose is to transfer a file
# from the client to the server
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
elif [ $# -eq 3 ]
then
	scp -o StrictHostKeyChecking=no $1 $3"@"$2":~/"
else
	scp -o StrictHostKeyChecking=no -i $4 $1 $3"@"$2":~/"
fi
