#!/usr/bin/env bash
# This script Updates a server and installs Nginx
# Also creates an html script to run in the web server
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
new_string = "location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}"
sed -i "s/location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files \$uri \$uri/ =404;
/$new_string/" /var/www/html/index.html
sudo service nginx restart
