#!/usr/bin/env bash
# This script installs Nginx and adds a custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error_str="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\troot /var/www/html;\n\tinternal;\n\t}"
sudo sed -i "36i $error_str" /etc/nginx/sites-available/default
sudo service nginx restart
