#!/usr/bin/env bash
# This is a bash init script for the file manage_my_processes.
FILE="/var/run/my_process.pid"

case "$1" in
	start)
		./manage_my_process &
		echo $! > $FILE
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat $FILE)"
		rm "$FILE"
		echo "manage_my_process stopped"
		;;
	restart)
		kill "$(cat $FILE)"
		./manage_my_process &
		echo $! > $FILE
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
