#!/usr/bin/env bash
# This is a bash init script for the file manage_my_processes.
FILE="/var/run/my_process.pid"

case "$1" in
	start)
		./manage_my_process &
		echo $! > $FILE
		echo "manage_my_process started"
		;;
	stop)
		pkill manage_my_process
		rm "/var/run/my_process.pid"
		echo "manage_my_process stopped"
		;;
	restart)
		pkill manage_my_process
		./manage_my_process &
		echo $! > $FILE
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|status|restart}"
		;;
esac
