#!/usr/bin/env bash
# This is a bash init script for the file manage_my_processes.
FILE=/var/run/my_process &

case "$1" in
	start)
		./manage_my_processes &
		echo $$ > $FILE
		echo "manage_my_process started"
		;;
	stop)
		pkill -f ./manage_my_process
		rm $FILE
		echo "manage_my_process stopped"
		;;
	restart)
		pkill -f ./manage_my_process
		rm $FILE
		./manage_my_processes &
		echo $$ > $FILE
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|status|restart}"
		;;
esac
