#!/usr/bin/env bash
# This script displays the contents of /etc/passwd usng a while loop and IFS
FILE="/etc/passwd"
while IFS=":" read -r -a line
do
	USERNAME="${line[0]}"
	GROUP_ID="${line[3]}"
	HOME_DIRECTORY="${line[5]}"
	COMMAND_OR_SHELL="${line[6]}"
	USER_ID="${line[2]}"
	PASSWORD="${line[1]}"
	USER_ID_INFO="${line[4]}"

	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_OR_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < $FILE
