#!/usr/bin/env bash
# Changes the localhost IP and facebook IP
cp /etc/hosts ~/hosts.new
sed -ie s/localhost/127.0.0.1/ /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
cp -f ~/hosts.new /etc/hosts
